-- MySQL Script generated by MySQL Workbench
-- Tue 19 Feb 2019 08:23:28 PM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Idaikkadu_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Idaikkadu_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Idaikkadu_db` DEFAULT CHARACTER SET latin1 ;
USE `Idaikkadu_db` ;

-- -----------------------------------------------------
-- Table `Idaikkadu_db`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Idaikkadu_db`.`auth_group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Idaikkadu_db`.`django_content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Idaikkadu_db`.`django_content_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label` ASC, `model` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Idaikkadu_db`.`auth_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Idaikkadu_db`.`auth_permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT(11) NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC),
  CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `Idaikkadu_db`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Idaikkadu_db`.`auth_group_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Idaikkadu_db`.`auth_group_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC),
  INDEX `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` (`permission_id` ASC),
  CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `Idaikkadu_db`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `Idaikkadu_db`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Idaikkadu_db`.`auth_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Idaikkadu_db`.`auth_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Idaikkadu_db`.`auth_user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Idaikkadu_db`.`auth_user_groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_groups_user_id_group_id_94350c0c_uniq` (`user_id` ASC, `group_id` ASC),
  INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` (`group_id` ASC),
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `Idaikkadu_db`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `Idaikkadu_db`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Idaikkadu_db`.`auth_user_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Idaikkadu_db`.`auth_user_user_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` (`user_id` ASC, `permission_id` ASC),
  INDEX `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm` (`permission_id` ASC),
  CONSTRAINT `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `Idaikkadu_db`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `Idaikkadu_db`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Idaikkadu_db`.`django_admin_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Idaikkadu_db`.`django_admin_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME(6) NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT(5) UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `django_admin_log_content_type_id_c4bce8eb_fk_django_co` (`content_type_id` ASC),
  INDEX `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id` ASC),
  CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `Idaikkadu_db`.`django_content_type` (`id`),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `Idaikkadu_db`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Idaikkadu_db`.`django_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Idaikkadu_db`.`django_migrations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Idaikkadu_db`.`django_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Idaikkadu_db`.`django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`session_key`),
  INDEX `django_session_expire_date_a5c62663` (`expire_date` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Idaikkadu_db`.`photos_album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Idaikkadu_db`.`photos_album` (
  `id` CHAR(32) NOT NULL,
  `title` VARCHAR(256) NOT NULL,
  `author` VARCHAR(128) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `menu` VARCHAR(1) NOT NULL,
  `approved` VARCHAR(1) NOT NULL,
  `countLike` SMALLINT(5) UNSIGNED NOT NULL,
  `countDisLike` SMALLINT(5) UNSIGNED NOT NULL,
  `imageDir` VARCHAR(100) NOT NULL,
  `link` VARCHAR(200) NOT NULL,
  `create_date` DATE NOT NULL,
  `release_date` DATE NOT NULL,
  `updated_by` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Idaikkadu_db`.`photos_photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Idaikkadu_db`.`photos_photo` (
  `id` CHAR(32) NOT NULL,
  `file` VARCHAR(100) NOT NULL,
  `countLike` SMALLINT(5) UNSIGNED NOT NULL,
  `countDisLike` SMALLINT(5) UNSIGNED NOT NULL,
  `create_date` DATE NOT NULL,
  `album_id` CHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `photos_photo_album_id_d37b4f12_fk_photos_album_id` (`album_id` ASC),
  CONSTRAINT `photos_photo_album_id_d37b4f12_fk_photos_album_id`
    FOREIGN KEY (`album_id`)
    REFERENCES `Idaikkadu_db`.`photos_album` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Idaikkadu_db`.`photos_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Idaikkadu_db`.`photos_comment` (
  `id` CHAR(32) NOT NULL,
  `comment` LONGTEXT NOT NULL,
  `updated_by` VARCHAR(128) NOT NULL,
  `create_date` DATE NOT NULL,
  `approved` VARCHAR(1) NOT NULL,
  `photo_id` CHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `photos_comment_photo_id_dcfe9eba_fk_photos_photo_id` (`photo_id` ASC),
  CONSTRAINT `photos_comment_photo_id_dcfe9eba_fk_photos_photo_id`
    FOREIGN KEY (`photo_id`)
    REFERENCES `Idaikkadu_db`.`photos_photo` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Idaikkadu_db`.`web_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Idaikkadu_db`.`web_content` (
  `id` CHAR(32) NOT NULL,
  `title` VARCHAR(256) NOT NULL,
  `author` VARCHAR(128) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `menu` VARCHAR(1) NOT NULL,
  `approved` VARCHAR(1) NOT NULL,
  `countLike` SMALLINT(5) UNSIGNED NOT NULL,
  `countDisLike` SMALLINT(5) UNSIGNED NOT NULL,
  `imageDir` VARCHAR(100) NOT NULL,
  `link` VARCHAR(200) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `document` VARCHAR(100) NOT NULL,
  `create_date` DATE NOT NULL,
  `release_date` DATE NOT NULL,
  `updated_by` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Idaikkadu_db`.`web_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Idaikkadu_db`.`web_comment` (
  `id` CHAR(32) NOT NULL,
  `comment` LONGTEXT NOT NULL,
  `updated_by` VARCHAR(128) NOT NULL,
  `create_date` DATE NOT NULL,
  `approved` VARCHAR(1) NOT NULL,
  `content_id` CHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `web_comment_content_id_7d5e87ac_fk_web_content_id` (`content_id` ASC),
  CONSTRAINT `web_comment_content_id_7d5e87ac_fk_web_content_id`
    FOREIGN KEY (`content_id`)
    REFERENCES `Idaikkadu_db`.`web_content` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
