# Generated by Django 2.1.7 on 2019-05-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('international', 'International'), ('srilanka', 'Sri Lanka'), ('idaikkadu', 'Idaikkadu')], default='international', max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(default='null', upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='default', max_length=255, unique=True),
        ),
    ]
