# Generated by Django 2.1.1 on 2018-11-03 15:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('updated_by', models.CharField(max_length=128)),
                ('create_date', models.DateField(auto_now=True)),
                ('approved', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(help_text='Author of the News or Article', max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('menu', models.CharField(choices=[('A', 'Australia'), ('C', 'Canada'), ('W', 'Swiss'), ('U', 'UK'), ('E', 'Europe'), ('U', 'Middle East'), ('S', 'School'), ('O', 'Associations'), ('T', 'Temples'), ('l', 'Libraries'), ('B', 'Articles'), ('D', 'Obituaries'), ('X', 'Other')], max_length=1)),
                ('approved', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('countLike', models.PositiveSmallIntegerField(default=0)),
                ('countDisLike', models.PositiveSmallIntegerField(default=0)),
                ('imageDir', models.FileField(upload_to='Image/%Y')),
                ('link', models.URLField(blank=True, help_text='Optional : any link to share')),
                ('create_date', models.DateField(auto_now=True)),
                ('release_date', models.DateField()),
                ('updated_by', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.Content')),
                ('imageFileName', models.ImageField(help_text='Please load one image here.', upload_to='Image%Y')),
                ('content', models.TextField()),
                ('document', models.FileField(blank=True, help_text='Optional : Any document in .pdf format', upload_to='')),
            ],
            bases=('web.content',),
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Content'),
        ),
    ]
