# Generated by Django 2.1.7 on 2019-05-01 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(help_text='Author of the News or Article', max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('menu', models.CharField(choices=[('A', 'Australia'), ('C', 'Canada'), ('W', 'Swiss'), ('U', 'UK'), ('E', 'Europe'), ('U', 'Middle East'), ('S', 'School'), ('O', 'Associations'), ('T', 'Temples'), ('l', 'Libraries'), ('B', 'Articles'), ('D', 'Obituaries'), ('X', 'Other')], max_length=1)),
                ('approved', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('countLike', models.PositiveSmallIntegerField(default=0)),
                ('countDisLike', models.PositiveSmallIntegerField(default=0)),
                ('imageDir', models.FileField(upload_to='Image/%Y')),
                ('link', models.URLField(blank=True, help_text='Optional : any link to share')),
                ('file', models.FileField(upload_to='photos/')),
                ('create_date', models.DateField(auto_now=True)),
                ('release_date', models.DateField(auto_now=True)),
                ('updated_by', models.CharField(max_length=128)),
            ],
        ),
    ]
