# Generated by Django 2.1.7 on 2019-05-08 06:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='a', max_length=256, unique=True)),
                ('description', models.CharField(default='a', max_length=256)),
                ('file', models.FileField(default='temp', upload_to='photos/')),
            ],
        ),
    ]
