# Generated by Django 2.1.1 on 2018-11-18 22:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(help_text='Author of the News or Article', max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('menu', models.CharField(choices=[('A', 'Australia'), ('C', 'Canada'), ('W', 'Swiss'), ('U', 'UK'), ('E', 'Europe'), ('U', 'Middle East'), ('S', 'School'), ('O', 'Associations'), ('T', 'Temples'), ('l', 'Libraries'), ('B', 'Articles'), ('D', 'Obituaries'), ('X', 'Other')], max_length=1)),
                ('approved', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('countLike', models.PositiveSmallIntegerField(default=0)),
                ('countDisLike', models.PositiveSmallIntegerField(default=0)),
                ('imageDir', models.FileField(upload_to='Image/%Y')),
                ('link', models.URLField(blank=True, help_text='Optional : any link to share')),
                ('create_date', models.DateField(auto_now=True)),
                ('release_date', models.DateField()),
                ('updated_by', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('updated_by', models.CharField(max_length=128)),
                ('create_date', models.DateField(auto_now=True)),
                ('approved', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='photos/')),
                ('countLike', models.PositiveSmallIntegerField(default=0)),
                ('countDisLike', models.PositiveSmallIntegerField(default=0)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.Album')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Photo'),
        ),
    ]
