# Generated by Django 2.1.7 on 2019-05-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='author',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='countDisLike',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='countLike',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='imageDir',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='link',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(default='temp', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default='a', max_length=256),
        ),
    ]
