# Generated by Django 2.2.1 on 2019-05-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(default='a', max_length=256),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default='a', max_length=256, unique=True),
        ),
    ]
